name: 'FIXME alert'
description: 'Check code for `FIXME:` and fail (with annotations) if any are found.'
author: '@bbugh'
branding:
  icon: 'list'  
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
